//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int ID { get; set; }
        public string Intro { get; set; }
        public string IntroE { get; set; }
        public string Content { get; set; }
        public string ContentE { get; set; }
        public string Address { get; set; }
        public string AddressE { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Photo { get; set; }
    }
}
