//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxAd
    {
        public int ID { get; set; }
        public string Photo { get; set; }
        public string Url { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Category { get; set; }
        public Nullable<byte> Location { get; set; }
    }
}
