//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public Nullable<byte> Category { get; set; }
        public Nullable<byte> CategoryDetail { get; set; }
        public Nullable<byte> CategoryDetailSub { get; set; }
        public string Title { get; set; }
        public string TitleE { get; set; }
        public string Content { get; set; }
        public string ContentE { get; set; }
        public string Photo { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<byte> IsHot { get; set; }
        public string Price { get; set; }
        public Nullable<byte> IsShowPrice { get; set; }
        public string Intro { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<byte> IsShowDefault { get; set; }
        public string FileAttach { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string PromotionPrice { get; set; }
        public Nullable<byte> IsMostView { get; set; }
        public Nullable<byte> IsNew { get; set; }
    }
}
