//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ID { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> CategorySub { get; set; }
        public string Title { get; set; }
        public string TitleE { get; set; }
        public string Content { get; set; }
        public string ContentE { get; set; }
        public string Photo { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> Location { get; set; }
        public string FileAttach { get; set; }
        public Nullable<byte> IsHot { get; set; }
        public Nullable<byte> IsHot1 { get; set; }
        public Nullable<byte> IsHot2 { get; set; }
        public Nullable<byte> IsHot3 { get; set; }
    }
}
